### ISSUE TITLE
Satisfaction survey feedback review

### ISSUE THREAD

**Issue by Manech-Laguens** [algosup/2023-2024-project-2-x86-retrogaming-team-6#12]
"New maze design:" 
put the ":" either with a space or stick it to the word, but not both. 

"reeived"
reviewed i guess. 

"ositive feedbacd" 
feedback + I think it's better to put it in plural except if there is only one feedback about it. 

" :Adding"
forgotten space 

" unlick"
 unlink ? unlike ? 

"positively recived.​​" 
I think you meant received 

"Mostly positive feedback," *
I'd say feedbacks, if u say mostly it means there are several innit ? 

"repsonded "
responded 

"Other ideas submitted"
Other submitted ideas 

"controles" then "controls" 

"preferences Collapse" 
wdym ?

**Comment by Biohazardyee** [comment]
Corrected all these mistakes
