### ISSUE TITLE
Test Plan Correction

### ISSUE THREAD

**Issue by Biohazardyee** [algosup/2023-2024-project-2-x86-retrogaming-team-6#8]
# Test Plan correction 

### Correction 
"introduction", no uppercase I.

"Here are" consider putting "here is what will be covered" or just put a table of content

In I. Unitary testing 1. Pac-Man movement : 
let --> left 
"dictated" please clarify. 

3. Ghost behavior: 
"We must ensure that every ghosts respects" --> "... ensure that every ghost respects" or "every ghosts respect" 

Blinky : he tracks Pac-Man and is always agressiv.
Pinky : she tries to predict Pac-Mans movements, and will position herslef in front of Pac-Man to trap him.
Inky : his movements are depending of Blinkys movements, as Pinky, he will try to trap Pac-Man.
Clyde : in opposition to the others, Clyde doesnt always chase Pac-Man ; if he's far of him, he will chase him down, but if he's too close, he will runaway.

consider removing in this part, "he", "she".
herslef --> herself 
Blinkys, Blinky's 
doesnt --> doesn't 

II. Integration testing 
1. Pac-Man's 
"when he mooves" --> moves
shouldnt --> shouldn't 

2.  Interactions between Pac-Man and the ghosts.
We have to ensure that each ghosts react and moove according to Pac-Man movments. --> "move.. movements"

3. Level transitions and screen menu.
We have to see if the screen transitions between levels and level to menu is smooth enough --> double check this, might be an iteration

4. Power-ups **integration** between Pac-Man and the ghosts.
you meant interaction here, right? 

their attitude toward Pac-Man change, they all try to escape, no matter their assigned behavior is. --> no matter what their assigned behavior is. attitude **changes** 

III. System testing.
game stability, fluidity
missing a point at the end 

1. Game stability.
the players --> the players' or the player's 

V. Update testing.
2. New features testing and backwards compatibility.
"that wil be impacted by the uptade."
that will be impacted by the update

VIII. Testing tools.
4. Environment.
(a faire check)
Quite french init 

X. Testing methodology.
part at the end of the document, not sure if it should be there.

### Conclusion
First version of the review, we'll go back to it once there's more to see, let me know whenever there's a big update on the document
- beware of the 's and n't

**Comment by Manech-Laguens** [comment]
The corrections have been taken into account and put in place.
